//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to the class structure, e.g. function names and parameters,
//     may cause incorrect behavior. Make changes only to each function body
//     in order to properly perform a migration
// </auto-generated>
//------------------------------------------------------------------------------

using MongoDB.Bson;
using MongoDB.Driver;

namespace Migrations
{
    public class M202501160001_CreateUserCollection
    {
        /// <summary>
        /// Downgrades a MongoDB database
        /// </summary>
        /// <param name="database">The MongoDB database instance</param>
        public bool Down(IMongoDatabase database)
        {
            database.DropCollection("users");
            return true;
        }

        /// <summary>
        /// Upgrades a MongoDB database
        /// </summary>
        /// <param name="database">The MongoDB database instance</param>
        public bool Up(IMongoDatabase database)
        {
            // Create users collection
            database.CreateCollection("users");
            
            // Create index on email field for uniqueness
            var usersCollection = database.GetCollection<BsonDocument>("users");
            var indexKeys = Builders<BsonDocument>.IndexKeys.Ascending("email");
            var indexOptions = new CreateIndexOptions { Unique = true };
            usersCollection.Indexes.CreateOne(new CreateIndexModel<BsonDocument>(indexKeys, indexOptions));

            return true;
        }
    }
}
