# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR Check Build and Tests

permissions:
  contents: read


on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - 'docker/**'

jobs:
  build-and-test:
    name: Build and Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal --configuration Release --filter "FullyQualifiedName!~E2E"

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Make test runner executable
      run: chmod +x ./scripts/run-e2e-tests.sh

    - name: Run E2E Tests
      run: ./scripts/run-e2e-tests.sh

    - name: Clean up Docker resources
      if: always()
      run: |
        docker compose -f docker/docker-compose.e2e.yml down -v --remove-orphans || true
        docker system prune -f || true
